apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-actions
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:damiao-santos/currencyconverterlab.git'
    targetRevision: HEAD
    path: argocd
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
