---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-keys
  namespace: default
spec:
  encryptedData:
    APIKEY: AgBevvqngqu/W944F54hQp3etnhXIJhjixBuTDD8m9zpyVxpg5iY2OL7RE+ymqDfw8Pe8Na5TAaqBp1yXkPg5forNdxFyYaWq/Y+MJoczIK4WI4yswHpP41gc+rBVb7Fyco5NU1cbKhXTfv9z3JxeQLlhNEtcEm0aqDMiLEvGRFaDC9JbYCP+wgKUQC1guYs7LiecNALWg8YGoink8V8ILFAyu/VcYcsG4M6k8RIzbhnEMQPPPhjEq3fzx2V3kyHKHiPwRZZLIhBihjW1YFjjmWN+bRcqF0+S2NhSFPXJWDHEW2tjnYjOKBasek0gRSU1Ax0uyokZIQl+Dpo0UuJTCwmRsax/FH2K9f3QZy1vIPQRIN7IUjeRD+BIDIMR54fDXJjU44WazZDJGXlvW4WhpIbQvY1HdUtaVwnq3OJJltmRMH1dsmKH90oaZ0JkzV8KOTxA3EMyulotrGaeN0OS226X2nBO09zFBmNFIHGNL9KrsLfuiptr3yJfGHRjrNiz/Izuny3J+aIKoIuZnRDEM77A9bagbMdr6dYq/wsO+TOVi0WBoeVmBUoP4K/70gAEr2uiC5Kv8FZoUoLe2P/h1ka+xPzl+7x6zOHcDzARRDRTNYkB0lQub04It6W7QTqmNXBDBAVk6teKCniOtTXVXxFBDTPs+S+zoSCa2AKNhLdTjYqKGnIA0Fc3RgCtlPcejQiQBG6eNyCW6oWIeDR+M5Uy8AiS/qv6aqpCPxLrQ3kLSFKcw+rQ3ZOt3cTBY2JXTXN270=
  template:
    metadata:
      creationTimestamp: null
      name: api-keys
      namespace: default
    type: Opaque
