---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: appsecret
  namespace: default
spec:
  encryptedData:
    APIKEY: AgARxXbZFj1J51e3Pk4MCCGJvkgxsz4xQd2Wr8eE0z1MSM2IsHtyWmaZe3kFeUx96aQ6Z1e757nXXtwu+6BrxJNxXKWOsHXVxgRt32NEbTh7BHX/g2dUC3VRTlQB+Eduo86vkRrCDYlzKRavLztAbc/JuSM/oR8juwDth3u0nR5yWnxaKF1hwCsytMkYEyvQ31scaL/GuqyC8fjpjEcJHOCtLGKA+TtEf1vgE0QWiWcrUvcPlLD20zHZvy4SavL6s/D7WiNj95vUR8Imor93WuXvhg22lvlGXrXpKSLAl7qqQrxjLJ1RnaK4tdlWiz5Cq56zXcvR9bWn4GHVoMbXSyeIIebCOwGyoAg+a/a6w/8bC8E0KDNTMRD7MntUtVA2fhglkoI5WHTGOj5DsUse44eTwHI9B7kl7EkQ2H8KzA7WNV5MG8LeO+IW2QZXeb9xWwryxWq7sJVyiUjuVRDdfu/arQ3jvDn8gEBy83nLGtba1K8a7Ko+I2xbKwWZR44JJ2CvCxcZ6KMIhr1902FBqJvRTwRRsbnnJtvW2cxOkk9iVLOuXP2nIl56ge23DkPISdDnX5hPwokTy3UP3+Zh6K4Uz9Ko6aES42KoE4SNDsmyTA6tSmaqmqC+NXq01ZpUBNo1CeaB+zOvHBSMQVzUFKTDEgJrzLVQmVGfmnZqVfzDI/ilF7szT9YDsE5s7CGfZXlo3I5sOKW9iRbF9fcm6l6oQt1/Qty7jgQ2uHhu8zira0Uj0jnjphpD0We+fgrtGHUqQZk=
  template:
    metadata:
      creationTimestamp: null
      name: appsecret
      namespace: default
    type: Opaque
